// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCategory(arg1:string):Promise<main.CategoryDTO>;

export function AddSubtask(arg1:number,arg2:string):Promise<main.SubtaskDTO>;

export function AddTask(arg1:string,arg2:string,arg3:string):Promise<main.TaskDTO>;

export function AssignCategory(arg1:number,arg2:number):Promise<main.TaskDTO>;

export function BulkComplete(arg1:Array<number>):Promise<number>;

export function BulkDelete(arg1:Array<number>):Promise<number>;

export function ClearCategory(arg1:number):Promise<main.TaskDTO>;

export function ClearCompleted():Promise<number>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteSubtask(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetCategories():Promise<Array<main.CategoryDTO>>;

export function GetStats():Promise<main.StatsDTO>;

export function GetSubtasks(arg1:number):Promise<Array<main.SubtaskDTO>>;

export function GetTasks(arg1:string):Promise<Array<main.TaskDTO>>;

export function SearchTasks(arg1:string):Promise<Array<main.TaskDTO>>;

export function SetTaskTags(arg1:number,arg2:Array<string>):Promise<main.TaskDTO>;

export function ToggleSubtask(arg1:number):Promise<main.SubtaskDTO>;

export function ToggleTask(arg1:number):Promise<main.TaskDTO>;

export function UpdateTask(arg1:number,arg2:string,arg3:string,arg4:string):Promise<main.TaskDTO>;
