// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:string,arg2:string,arg3:string):Promise<main.TaskDTO>;

export function ClearCompleted():Promise<number>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetStats():Promise<main.StatsDTO>;

export function GetTasks(arg1:string):Promise<Array<main.TaskDTO>>;

export function ToggleTask(arg1:number):Promise<main.TaskDTO>;

export function UpdateTask(arg1:number,arg2:string,arg3:string,arg4:string):Promise<main.TaskDTO>;
