// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function AddSubtask(arg1, arg2) {
  return window['go']['main']['App']['AddSubtask'](arg1, arg2);
}

export function AddTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTask'](arg1, arg2, arg3);
}

export function AssignCategory(arg1, arg2) {
  return window['go']['main']['App']['AssignCategory'](arg1, arg2);
}

export function BulkComplete(arg1) {
  return window['go']['main']['App']['BulkComplete'](arg1);
}

export function BulkDelete(arg1) {
  return window['go']['main']['App']['BulkDelete'](arg1);
}

export function ClearCategory(arg1) {
  return window['go']['main']['App']['ClearCategory'](arg1);
}

export function ClearCompleted() {
  return window['go']['main']['App']['ClearCompleted']();
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteSubtask(arg1) {
  return window['go']['main']['App']['DeleteSubtask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetSubtasks(arg1) {
  return window['go']['main']['App']['GetSubtasks'](arg1);
}

export function GetTasks(arg1) {
  return window['go']['main']['App']['GetTasks'](arg1);
}

export function SearchTasks(arg1) {
  return window['go']['main']['App']['SearchTasks'](arg1);
}

export function SetTaskTags(arg1, arg2) {
  return window['go']['main']['App']['SetTaskTags'](arg1, arg2);
}

export function ToggleSubtask(arg1) {
  return window['go']['main']['App']['ToggleSubtask'](arg1);
}

export function ToggleTask(arg1) {
  return window['go']['main']['App']['ToggleTask'](arg1);
}

export function UpdateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3, arg4);
}
